name: threshold_eng_apps
description: A Flutter plugin for getting information about apps made by Threshold Engineering.
version: 2.0.0
author: Threshold Engineering
homepage: https://www.thresholdeng.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
